Proyecto/Proyecto/Models/curriculum.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public curriculum()
        {
            this.candidatos_ofertas = new HashSet<candidatos_ofertas>();
            this.cv_exp_laboral = new HashSet<cv_exp_laboral>();
            this.cv_form_academica = new HashSet<cv_form_academica>();
            this.cv_idiomas = new HashSet<cv_idiomas>();
            this.cv_ref_profesionales = new HashSet<cv_ref_profesionales>();
        }
    
        public int id_curriculum { get; set; }

        [Required(ErrorMessage = "Ingrese el usuario")]
        [Display(Name = "Usuario")]
        public int id_usuario { get; set; }

        [Required(ErrorMessage = "Ingrese su fotografia")]
        [Display(Name = "Fotografia")]
        public string fotografia { get; set; }

        [Required(ErrorMessage = "Ingrese su fecha de nacimiento")]
        [Display(Name = "Fecha nacimiento")]
        public System.DateTime fechaNacimiento { get; set; }

        [Required(ErrorMessage = "Ingrese su dirección")]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }

        [Required(ErrorMessage = "Ingrese su telefono")]
        [Display(Name = "Telefono")]
        [RegularExpression(@"[267]\d{3}-\d{4}$", ErrorMessage = "Formato de telefono incorrecto")]
        public string numeroTelefono { get; set; }

        [Required(ErrorMessage = "Ingrese su dui")]
        [Display(Name = "Telefono")]
        [RegularExpression(@"[0-9]{8}\d-\d{1}$", ErrorMessage = "Formato de dui incorrecto")]
        public string dui { get; set; }

        [Required(ErrorMessage = "Ingrese su genero")]
        [Display(Name = "Genero")]
        public string sexo { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatos_ofertas> candidatos_ofertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_exp_laboral> cv_exp_laboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_form_academica> cv_form_academica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_idiomas> cv_idiomas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_ref_profesionales> cv_ref_profesionales { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}

Proyecto/Proyecto/Models/idiomas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class idiomas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idiomas()
        {
            this.cv_idiomas = new HashSet<cv_idiomas>();
        }
    
        public int id_idioma { get; set; }

        [Required(ErrorMessage = "Ingrese el idioma")]
        [Display(Name = "Idioma")]
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_idiomas> cv_idiomas { get; set; }
    }
}

Proyecto/Proyecto/Controllers/CurriculumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto.Models;
using WebApplication3.Models;

namespace Proyecto.Controllers
{
    public class CurriculumController : Controller
    {
        usuariosModel ni = new usuariosModel();
        curriculumModel model = new curriculumModel();
        idiomasModel idioma = new idiomasModel();
        cv_IdiomaModel cvIdioma = new cv_IdiomaModel();
        form_academicaModel model1 = new form_academicaModel();
        cv_FormacionModel model2 = new cv_FormacionModel();

        // GET: Curriculum
        public ActionResult Index()
        {
            return View();
        }

        // POST: Curriculum
        [HttpPost]
        public ActionResult Index(string date, curriculum curriculum, string sexo, string foto)
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum.id_usuario = us.id_usuario;
            curriculum.fechaNacimiento = Convert.ToDateTime(date);
            curriculum.sexo = sexo;
            curriculum.fotografia = foto;
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Insert(curriculum) > 0)
                    {
                        TempData["successMessage"] = "Primer Paso Ingresado";
                        return RedirectToAction("Idioma");
                    }
                }
            }
            catch
            {

            }
            return View();
        }

        // PARTE DE IDIOMAS

        public ActionResult Idioma()
        {
            usuarios us = (usuarios)Session["usuario"];
            
            curriculum candidato = model.idCurriculum(us.id_usuario);
            if (candidato == null)
            {
                return View("Index");
            }
            else
            {
                ViewBag.idIdioma = idioma.List();
                ViewBag.Lista = cvIdioma.idiomasCandidato(candidato.id_curriculum);
                ViewBag.Idiomas = idioma.ListaIdiomas();
                return View();
            }
        }

        [HttpGet]
        public ActionResult Idioma(int? id)
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum candidato = model.idCurriculum(us.id_usuario);
            ViewBag.idIdioma = idioma.List();
            ViewBag.Lista = cvIdioma.idiomasCandidato(candidato.id_curriculum);
            ViewBag.Idiomas = idioma.ListaIdiomas();
            if (id == null)
            {
                return View("Idioma");
            }
            int an = Convert.ToInt32(id);
            cv_idiomas bell = cvIdioma.id_cv_idioma(an);
            try
            {
                if (bell == null)
                {
                    return View("Idioma");
                }
                else
                {
                    if (cvIdioma.Remove(an) > 0)
                    {
                        return RedirectToAction("Idioma");
                    }
                    ViewBag.errorB = "ERROR: AL ELIMINAR EL IDIOMA";
                    return View("Idioma");
                }
            }
            catch
            {
                ViewBag.errorB = "ERROR: AL ELIMINAR EL IDIOMA";
                return View("Idioma");
            }
        }

        [HttpPost]
        public ActionResult Idioma(string idioma1)
        {
            usuarios us = (usuarios)Session["usuario"];
            int lang = Convert.ToInt32(idioma1);
            curriculum candidato = model.idCurriculum(us.id_usuario);

            ViewBag.idIdioma = idioma.List();
            ViewBag.Lista = cvIdioma.idiomasCandidato(candidato.id_curriculum);
            ViewBag.Idiomas = idioma.ListaIdiomas();

            if(candidato == null)
            {
                return View("Index");
            }
            else
            {
                cv_idiomas validacion = cvIdioma.idIdioma(lang, candidato.id_curriculum);
                if (validacion == null)
                {
                    try
                    {
                        cv_idiomas bell = new cv_idiomas();
                        bell.id_curriculum = candidato.id_curriculum;
                        bell.id_idioma = lang;
                        if (cvIdioma.Insert(bell) > 0)
                        {

                            ViewBag.errorB = "Idioma Ingresado";
                            return RedirectToAction("Idioma");
                        }
                        else
                        {
                            ViewBag.errorB = "Ya ha ingresado ha este idioma";
                            return View("Idioma");
                        } 
                    }
                    catch
                    {
                        ViewBag.errorB = "ERROR";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.idIdioma = idioma.List();
                    ViewBag.Lista = cvIdioma.idiomasCandidato(candidato.id_curriculum);
                    ViewBag.Idiomas = idioma.ListaIdiomas();
                    ViewBag.errorB = "Ya ha ingresado este idioma";
                    return View("Idioma");
                }
            }
        }

        // PARTE DE FORM_ACADEMICA


        public ActionResult FormacionAcademica()
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum an = model.idCurriculum(us.id_usuario);
            ViewBag.FormA = model2.FormacionCandidato(an.id_curriculum);
            ViewBag.Form = model1.List();

            return View();
        }

        [HttpGet]
        public ActionResult FormacionAcademica(int? id)
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum an = model.idCurriculum(us.id_usuario);
            ViewBag.FormA = model2.FormacionCandidato(an.id_curriculum);
            ViewBag.Form = model1.List();
            if (id == null)
            {
                return View("FormacionAcademica");
            }
            int idForm = Convert.ToInt32(id);
            cv_form_academica obj = model2.ObjetoFormacion(an.id_curriculum, idForm);
            
            try
            {
                if (obj == null)
                {
                    return View("FormacionAcademica");
                }
                else
                {
                    int x = obj.id_form_academica;
                    if (model2.Remove(obj.id_cv_form_academica) > 0)
                    {
                        if (model1.Remove(x)>0)
                        {
                            return RedirectToAction("FormacionAcademica");
                        }
                        
                    }
                    ViewBag.errorB = "ERROR: AL ELIMINAR LA FORMACION";
                    return View("FormacionAcademica");
                }
            }
            catch
            {
                ViewBag.errorB = "ERROR: AL ELIMINAR EL IDIOMA";
                return View("Idioma");
            }

        }

        [HttpPost]
        public ActionResult FormacionAcademica(string tipo, string inicio, string fin, form_academica formacion)
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum an = model.idCurriculum(us.id_usuario);
            ViewBag.FormA = model2.FormacionCandidato(an.id_curriculum);
            ViewBag.Form = model1.List();

            if (inicio.Length == 0 || fin.Length == 0)
            {
                ViewBag.errorB = "Ingrese las Fechas";
                return View();
            }
            formacion.tipo_educacion = tipo;
            formacion.fech_inicio = Convert.ToDateTime(inicio);
            formacion.fech_fin = Convert.ToDateTime(fin);

            try
            {
                if (ModelState.IsValid)
                {
                    if (model1.Insert(formacion) > 0)
                    {
                        cv_form_academica bell = new cv_form_academica();
                        bell.id_curriculum = an.id_curriculum;
                        bell.id_form_academica = formacion.id_form_academica;
                        if (model2.Insert(bell) > 0)
                        {
                            ViewBag.errorB = "Formacion Academica Ingresado";
                            return RedirectToAction("FormacionAcademica");
                        }
                        ViewBag.errorB = "ERROR3";
                        return View();
                    }
                    ViewBag.errorB = "ERROR2";
                    return View();
                }
                else
                {
                    ViewBag.errorB = "ERROR";
                    return View();
                }
            }
            catch
            {
                return View();
            }
            
        }


        /* EXPERIENCIA LABORAL */
        exp_profesionalModel model5 = new exp_profesionalModel();
        cv_ExpModel model6 = new cv_ExpModel();

        public ActionResult ExperienciaLaboral()
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum an = model.idCurriculum(us.id_usuario);
            ViewBag.FormA = model6.ListaExp(an.id_curriculum);
            ViewBag.Form = model5.List();
            return View();
        }

        [HttpGet]
        public ActionResult ExperienciaLaboral(int? id)
        {
            usuarios us = (usuarios)Session["usuario"];
            curriculum an = model.idCurriculum(us.id_usuario);
            ViewBag.FormA = model6.ListaExp(an.id_curriculum);
            ViewBag.Form = model5.List();
            if (id == null)
            {
                return View("ExperienciaLaboral");
            }

            int idExp = Convert.ToInt32(id);
            cv_exp_laboral obj = model6.ObjetoExp(an.id_curriculum, idExp);
            

Proyecto/Proyecto/Views/Curriculum/ExperienciaLaboral.cshtml
@model Proyecto.Models.exp_profesional

@{
    ViewBag.Title = "ExperienciaLaboral";
}

<h2>Crear Curriculum</h2>
<h3>Cuarto Paso: Experiencia Laboral</h3>

@using (Html.BeginForm("ExperienciaLaboral", "Curriculum", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h4 style="color: red;">@ViewBag.errorB</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jefe_inmediato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jefe_inmediato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jefe_inmediato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fech_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="inicio" name="inicio" type="date" required>
                @Html.ValidationMessageFor(model => model.fech_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fech_fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="fin" name="fin" type="date" required>
                @Html.ValidationMessageFor(model => model.fech_fin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ingresar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br />
<div class="container" style="width:100%;margin:auto;">
    <a href="Referencia" class="btn btn-success">Siguiente</a>
</div>
<br />
<h3>Lista de Experiencias Laborales</h3>
<table class="table table-hover" style="width:100%;border: none;margin:auto;">
    <tr>
        <th style="text-align:center;">
            Empresa
        </th>
        <th style="text-align:center;">
            Cargo
        </th>
        <th style="text-align:center;">
            Jefe Inmediato
        </th>
        <th style="text-align:center;">
            Fecha de Inicio
        </th>
        <th style="text-align:center;">
            Fecha de Fin
        </th>
        <th style="text-align:center;">
            Salario $
        </th>
    </tr>

    @foreach (var item in @ViewBag.FormA)
    {
    <tr>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_cv_exp_laboral == item1.id_exp_profesional)
                {
                    @item1.empresa
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_cv_exp_laboral == item1.id_exp_profesional)
                {
                    @item1.cargo
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_cv_exp_laboral == item1.id_exp_profesional)
                {
                    @item1.jefe_inmediato
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_cv_exp_laboral == item1.id_exp_profesional)
                {
                    @item1.fech_inicio
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_cv_exp_laboral == item1.id_exp_profesional)
                {
                    @item1.fech_fin
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_cv_exp_laboral == item1.id_exp_profesional)
                {
                    @item1.salario
                }
            }
        </td>
        <td style="text-align:center;">
            @Html.ActionLink("Eliminar", "ExperienciaLaboral", new { id = item.id_cv_exp_laboral }, new { @class = "btn btn-danger", @onclick = "return confirm('Esta seguro que desea eliminar esta experiencia laboral?')" })
        </td>
    </tr>
    }
</table>

Proyecto/Proyecto/Views/Curriculum/FormacionAcademica.cshtml
@model Proyecto.Models.form_academica

@{
    ViewBag.Title = "FormacionAcademica";
}
 
<h2>Crear Curriculum</h2>
<h3>Tercer Paso: Formacion Academica</h3>

@using (Html.BeginForm("FormacionAcademica", "Curriculum", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <h4 style="color: red;">@ViewBag.errorB</h4>

    <div class="form-group">
        @Html.LabelFor(model => model.titulo_obtenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.titulo_obtenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.titulo_obtenido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.institucion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.institucion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.institucion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tipo_educacion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="tipo" name="tipo">
                <option value="Educación Basica" selected>Educación Basica</option>
                <option value="Educación Media">Educación Media</option>
                <option value="Ingenieria">Ingenieria</option>
                <option value="Licenciatura">Licenciatura</option>
                <option value="Maestria">Maestria</option>
                <option value="Tecnico">Tecnico</option>
                <option value="Diplomado">Diplomado</option>
                <option value="Doctorado">Doctorado</option>
            </select>
            @Html.ValidationMessageFor(model => model.tipo_educacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fech_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input id="inicio" name="inicio" type="date" required>
            @Html.ValidationMessageFor(model => model.fech_inicio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fech_fin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input id="fin" name="fin" type="date" required>
            @Html.ValidationMessageFor(model => model.fech_fin, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Agregar" class="btn btn-default" />
        </div>
    </div>
</div>
}
<br />
<div class="container" style="width:100%;margin:auto;">
    <a href="ExperienciaLaboral" class="btn btn-success">Siguiente</a>
</div>
<br />
<h3>Lista de Formación Academica</h3>
<table class="table table-hover" style="width:100%;border: none;margin:auto;">
    <tr>
        <th style="text-align:center;">
            Titulo Obtenido
        </th>
        <th style="text-align:center;">
            Institucion
        </th>
        <th style="text-align:center;">
            Tipo de Educación
        </th>
        <th style="text-align:center;">
            Fecha de Inicio
        </th>
        <th style="text-align:center;">
            Fecha de Fin
        </th>
    </tr>

    @foreach (var item in @ViewBag.FormA)
    {
    <tr>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_form_academica == item1.id_form_academica)
                {
                    @item1.titulo_obtenido
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_form_academica == item1.id_form_academica)
                {
                    @item1.institucion
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_form_academica == item1.id_form_academica)
                {
                    @item1.tipo_educacion
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_form_academica == item1.id_form_academica)
                {
                    @item1.fech_inicio
                }
            }
        </td>
        <td style="text-align:center;">
            @foreach (var item1 in @ViewBag.Form)
            {
                if (item.id_form_academica == item1.id_form_academica)
                {
                    @Convert.ToDateTime(item1.fech_fin)
                }
            }
        </td>
        <td style="text-align:center;">
            @Html.ActionLink("Eliminar", "FormacionAcademica", new { id = item.id_cv_form_academica }, new { @class = "btn btn-danger", @onclick = "return confirm('Esta seguro que desea eliminar esta formación?')" })
        </td>
    </tr>
    }
</table>

Proyecto/Proyecto/Views/Curriculum/Idioma.cshtml
@model Proyecto.Models.cv_idiomas

@{
    ViewBag.Title = "Idioma";
}

<h2>Crear Curriculum</h2>
<h4>Segundo Paso: Idiomas</h4>

@using (Html.BeginForm("Idioma", "Curriculum", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <h4 style="color: red;">@ViewBag.errorB</h4>
        <div class="form-group">
            @Html.LabelFor(model => model.id_idioma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" id="idioma1" name="idioma1">
                    @foreach (var item in @ViewBag.idIdioma)
                    {
                        <option value="@item.id_idioma">@item.nombre</option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.id_idioma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br />
<div class="container" sstyle="width:100%;margin:auto;">
    <a href="FormacionAcademica" class="btn btn-success">Siguiente</a>
</div>
<h3>Lista de Idiomas</h3>
<table class="table table-hover" style="width:50%;border: none;margin:auto;">
    <tr>
        <th style="text-align:center;">
            Idiomas
        </th>
        <th>
            
        </th>

    </tr>

    @foreach (var item in @ViewBag.Lista)
    {
        <tr>
            <td style="text-align:center;">
                @foreach (var item1 in @ViewBag.Idiomas)
                {
                    if (item.id_idioma == item1.id_idioma)
                    {
                        @item1.nombre
                    }
                }
            </td>
            <td style="text-align:center;">
                @Html.ActionLink("Eliminar", "Idioma", new { id = item.id_cv_idiomas }, new { @class = "btn btn-danger", @onclick = "return confirm('Esta seguro que desea eliminar este idioma?')" })
            </td>
        </tr>
    }

</table>