Proyecto/Proyecto/Controllers/IngresarCandidatoController.cs
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto.utils;
using System.Net.Mail;
using System.Net;
using System.Diagnostics;

namespace Proyecto.Controllers
{
    public class IngresarCandidatoController : Controller
    {

        usuariosModel model = new usuariosModel();

        // GET: IngresarCandidato
        public ActionResult Index()
        {
            return View();
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        [HttpPost]
        public ActionResult Create(usuarios candidato)
        {
            string c1, c2;
            candidato.id_tipo_usuario = 4;//tipo candidato
            candidato.password = (SecurityUtils.EncriptarSHA2(candidato.password));//emcriptando contraseña
            candidato.estado = 0;//estado no veirficado
            
            
            //generando codigo
            c1 = candidato.apellido1.Substring(0, 1);
            c2 = candidato.apellido2.Substring(0, 1);

            //Random randomGenerate = new Random();
            //string sPassword = "";
            //sPassword = Convert.ToString(randomGenerate.Next(00000001, 99999999));
            //sPassword.Substring(sPassword.Length - 8, 8);
            Random rdn = new Random();
            int a = rdn.Next(1000000, 99999999);
            string num = a.ToString();
            //agregando codigo
            candidato.codigo = c1 + c2 + num;
            
            try
            {
                //if (ModelState.IsValid)
                //{
                    
                    if (model.Insert(candidato) > 0)
                    {
                        validarUsuario(candidato.email, candidato.codigo);
                        TempData["successMessage"] = "Verifique su correo para validar su registro";
                        return RedirectToAction("Validar");
                    }
                //    TempData["successMessage"] = "Error al ingresar el candidato";
                //}
                return View(candidato);
            }
            catch(Exception e)
            {
                Debug.WriteLine(e);
                return View();
            }
        }

        //Ruta para ingresar el codigo de validacion de cuenta
        public ActionResult Validar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Validar(string codigo)
        {
            Debug.WriteLine(codigo);
            if (string.IsNullOrWhiteSpace(codigo))
            {
                ModelState.AddModelError("email", "Debes ingresar el codigo");
            }
            if (!ModelState.IsValid)
            {
                return View(ModelState);
            }
            usuarios user = model.validarCodigo(codigo);
            if (user == null)
            {
                ModelState.AddModelError("email", "Código de validación incorrecto");
                return View(ModelState);
            }
            else
            {
                try
                {
                    user.estado = 1;
                    if (model.Update(user, user.id_usuario) > 0)
                    {
                        ModelState.AddModelError("email", "Su cuenta ha sido validada");
                        return View("Validar", ModelState);
                    }
                    ModelState.AddModelError("email", "ERROR");
                    return View("Validar", ModelState);
                }
                catch
                {
                    ModelState.AddModelError("email", "ERROR 2");
                    return View("Validar", ModelState);
                }
            }
        }

        public void validarUsuario(string emailDestino, string codigo)
        {
            string asunto = "Validar registro de usuario";

            MailMessage msg = new MailMessage();
            msg.To.Add(emailDestino);

            msg.From = new MailAddress("bolsatrabajo76@gmail.com", "Bolsa de Trabajo SV", System.Text.Encoding.UTF8);
            msg.Subject = asunto;
            msg.SubjectEncoding = System.Text.Encoding.UTF8;
            msg.Body = string.Format("<h2>Bolsa de Trabajo</h2>" +
                "<p>Te damos la bienvenida a Bolsa de Trabajo SV, ahora podras disfrutar de los diferentes beneficios que te ofrece.</p>" +
                "Ingrese este codigo para validar su cuenta en Bolsa de Trabajo: <b>{0}</b>" +
                "<br>" +
                "<p>Si no has solicitado este codigo, ignorar este mensaje.</p>", codigo);
            msg.BodyEncoding = System.Text.Encoding.UTF8;
            msg.IsBodyHtml = true;
            msg.Priority = MailPriority.High;

            SmtpClient cliente = new SmtpClient();
            cliente.Credentials = new NetworkCredential("bolsatrabajo76@gmail.com", "bolsa1234");
            cliente.Port = 25;
            cliente.Host = "smtp.gmail.com";
            cliente.EnableSsl = true;
            try
            {
                cliente.Send(msg);
            }
            catch (SmtpException ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadLine();
            }
        }
    }
}

Proyecto/Proyecto/Views/IngresarCandidato/Create.cshtml
@model Proyecto.Models.usuarios

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "IngresarCandidato", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>usuarios</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.apellido1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellido1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.apellido1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.apellido2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellido2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.apellido2, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto/Proyecto/Views/IngresarCandidato/Validar.cshtml
@{
    ViewBag.Title = "Validar";
}

<h2>Validar</h2>
<div class="container">
    <div class="row">
        <div class="col-sm-offset-4 col-sm-4 ">
            <h2>Validar Cuenta</h2>

            @using (Html.BeginForm("Validar", "IngresarCandidato", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label>Ingrese el codigo:</label>
                    <input type="text" name="codigo" id="codigo" class="form-control" />
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-lg btn-primary btn-block">Iniciar sesion</button>
                    @*<a href="/login" class="btn btn-lg btn-primary btn-block">Iniciar sesion</a>*@
                </div>
            }
        </div>
    </div>
</div>